<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <CopyDebugSymbolFilesFromPackages>true</CopyDebugSymbolFilesFromPackages>
    <Description>IntegrationMocks Yugabyte binding.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <!--
  <ItemGroup>
    <PackageReference Include="Testcontainers" Version="3.8.0" />
  </ItemGroup>
  -->
  <ItemGroup>
    <ProjectReference Include="..\IntegrationMocks.Core\IntegrationMocks.Core.csproj" />
    <ProjectReference Include="..\IntegrationMocks.Modules.Testcontainers\IntegrationMocks.Modules.Testcontainers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
